### ISSUE TITLE
Build a new version of the fluent-bit plugin

### ISSUE THREAD

**Issue by Photonios** [coralogix/integrations-docs#42]
Following the merge of: https://github.com/coralogix/integrations-docs/pull/41

Can we have a new build of https://hub.docker.com/r/coralogixrepo/fluent-bit-coralogix-image and https://github.com/coralogix/integrations-docs/blob/master/integrations/fluent-bit/plugin/out_coralogix.so ?

**Comment by EldarAliiev** [comment]
Working on that.

**Comment by EldarAliiev** [comment]
@Photonios updated **.so** file added to repo, about new images:
```
coralogixrepo/fluent-bit-coralogix-image:1.7.6
coralogixrepo/fluent-bit-coralogix-image:latest
```
